name: upma
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.1
  photo_manager: ^3.6.4
  googleapis: ^13.1.0
  googleapis_auth: ^1.6.0
  image_picker: ^1.1.2
  http: ^1.2.1
  file_picker: ^6.1.1
  intl: ^0.18.1
  image: ^4.0.17
  workmanager: ^0.5.2
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.0 
  flutter_background_service_ios: ^5.0.0
  flutter_background_service: ^5.0.0
  share_plus: ^10.0.0
  url_launcher: ^6.3.1
  animate_do: ^4.2.0
  google_fonts: ^6.1.0
  flutter_vibrate: ^1.3.0
  persistent_bottom_nav_bar_v2: ^5.3.1
  curved_navigation_bar: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
  uses-material-design: true
  assets:
    - assets/app_icon.png
    - assets/credentials.json